version: "3.9"

# Run 'docker compose up' to start all containers

# Default Network
networks:
  app-network:
    driver: bridge

services:

  # ETCD Server
  etcd:
    image: 'bitnami/etcd:3.4.15'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - app-network

  # Memcached Server
  memcached:
    image: 'bitnami/memcached:1.6.9'
    networks:
      - app-network

  geoserver:
    image: 'scalapb-demo:0.1.0-SNAPSHOT'
    entrypoint: '/opt/docker/bin/geo-server'
    depends_on:
      - etcd
    networks:
      - app-network

  geoclient:
    image: 'scalapb-demo:0.1.0-SNAPSHOT'
    entrypoint: '/opt/docker/bin/geo-client-demo-2'
    depends_on:
      - etcd
      - geoserver
    networks:
      - app-network
    volumes:
      - ./txts/:/txts/