apiVersion: apps/v1
kind: Deployment
metadata:
  name: geo-server-deployment
  labels:
    app: geo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geo-server
  template:
    metadata:
      labels:
        app: geo-server
    spec:
      containers:
      - name: geo-server
        image: scalapb-demo:0.1.0-SNAPSHOT
        imagePullPolicy: Never
        ports:
        - containerPort: 50000