apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-deployment
  labels:
    app: memcached
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: bitnami/memcached:1.6.9
        ports:
        - containerPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: memcached
  name: memcached
spec:
  selector:
    app: memcached
  ports:
    - port: 11211